### ISSUE TITLE
Data not distributed equally between two nodes

### ISSUE THREAD

**Issue by mrajmohan1999** [cnblogs/EnyimMemcachedCore#199]
I left a comment earlier that got removed so reposting this. I am facing an issue where I have two servers configured, but only one of them is being hit and storing data. One has 0 hits and the other has ~95% hit rate. This issue recently started about a couple months ago and we haven't made any changes on how the nodes are configured on our end. Both servers are alive and reachable so it isn't the issue of one server being down. The only error we have found is in the Read() method:

stack trace:
at Enyim.Caching.Memcached.PooledSocket.Read(Byte[] buffer, Int32 offset, Int32 count)
at Enyim.Caching.Memcached.Protocol.Binary.BinaryResponse.Read(PooledSocket socket)
at Enyim.Caching.Memcached.Protocol.Binary.BinarySingleItemOperation.ReadResponse(PooledSocket socket)

We tried using the text protocol as well as the binary and faced the same issue.

**Comment by adison88** [comment]
@cnblogs-dudu could you please help check on this issue?

**Comment by cnblogs-dudu** [comment]
Please telnet memcached servers and check `curr_connections` from `stats`.

**Comment by mrajmohan1999** [comment]
One node has a very small number of curr_connections (2) while the other has a lot more (over 20)
