### ISSUE TITLE
System.ArgumentOutOfRangeException when calling GetWithCas

### ISSUE THREAD

**Issue by damiancosmoschapman** [cnblogs/EnyimMemcachedCore#211]
We are getting a System.ArgumentOutOfRangeException when calling GetWithCas.

We are using 

memcached service version - 1.6.18
EnyimMemcachedCore version - 2.6.6

We are getting the following exception when calling GetWithCas as follows:

`GetWithCas<List<string>>(repository) // where repository is a string`

```
System.ArgumentOutOfRangeException: Unexpected BsonType value: 0 (Parameter 'type')
   at Newtonsoft.Json.Bson.BsonDataReader.ReadType(BsonType type) in /_/Src/Newtonsoft.Json.Bson/BsonDataReader.cs:line 578
   at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal() in /_/Src/Newtonsoft.Json.Bson/BsonDataReader.cs:line 376
   at Newtonsoft.Json.Bson.BsonDataReader.Read() in /_/Src/Newtonsoft.Json.Bson/BsonDataReader.cs:line 205
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Enyim.Caching.Memcached.DefaultTranscoder.Deserialize[T](CacheItem item)
   at Enyim.Caching.MemcachedClient.PerformTryGet[T](String key, UInt64& cas, T& value)
   at Enyim.Caching.MemcachedClient.TryGetWithCas[T](String key, CasResult`1& value)
   at Enyim.Caching.MemcachedClient.GetWithCas[T](String key)
```

We have also tried using the MessagePackTranscoder, by adding it as part of the memcached settings, in appsettings.json but we are getting a similar exception error.

**Comment by cnblogs-dudu** [comment]
This exception can not be reproduced with `GetWithCas<T>`. can you provide more details?
