### ISSUE TITLE
.net core 2.0 启动时报错

### ISSUE THREAD

**Issue by kernelj** [cnblogs/EnyimMemcachedCore#41]
fail: Enyim.Caching.Configuration.MemcachedClientConfiguration[24311045]
      Create PooledSocket
System.TimeoutException: Could not connect to Unspecified/memcached:11211
   at Enyim.Caching.Memcached.PooledSocket.ConnectWithTimeout(Socket socket, EndPoint endpoint, Int32 timeout)
   at Enyim.Caching.Memcached.PooledSocket..ctor(EndPoint endpoint, TimeSpan connectionTimeout, TimeSpan receiveTimeout, ILogger logger)
   at Enyim.Caching.Memcached.MemcachedNode.CreateSocket()
fail: Enyim.Caching.Configuration.MemcachedClientConfiguration[0]
      Could not init pool.
warn: Enyim.Caching.Configuration.MemcachedClientConfiguration[0]
      Marking node Unspecified/memcached:11211 as dead
EnyimMemcached Started.
Hosting environment: Development

**Comment by cnblogs-dudu** [comment]
Add  a new entry for `memcached` in  hosts file.

**Comment by kernelj** [comment]
要改 hosts 文件吗，要怎么改？
