### ISSUE TITLE
更新到2.1.10版本时，出现读取缓存错误

### ISSUE THREAD

**Issue by TimSteve** [cnblogs/EnyimMemcachedCore#85]
**运行环境**
* ubuntu 16.04

**Core版本**
* 2.2.0

**EnyimMemcachedCore版本**
* 2.1.10

**错误日志**

```
2018-12-27 01:01:00.927 +08:00 [Error] GetAsync("test-cachekey")
System.ArgumentOutOfRangeException: Unexpected BsonType value: 0
Parameter name: type
   at Newtonsoft.Json.Bson.BsonDataReader.ReadType(BsonType type)
   at Newtonsoft.Json.Bson.BsonDataReader.ReadNormal()
   at Newtonsoft.Json.Bson.BsonDataReader.Read()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Enyim.Caching.Memcached.DefaultTranscoder.Deserialize[T](CacheItem item)
   at Enyim.Caching.MemcachedClient.BuildGetCommandResult[T](IGetOperationResult`1 result, IGetOperation command, IOperationResult commandResult)
   at Enyim.Caching.MemcachedClient.GetAsync[T](String key)
```

**Comment by TimSteve** [comment]
在使用 `2.1.8`版本的时候没有这个问题。

**Comment by TimSteve** [comment]
#79 一样错误日志

**Comment by cnblogs-dudu** [comment]
Fixed in EnyimMemcachedCore 2.1.11.
